# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: V²Shop
email: villagehubertchen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the Shop of Vilagetronic.
baseurl: "/shop" # the subpath of your site, e.g. /blog
url: "https://v-squared.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: villagevidock
github_username:  v-squared

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - octopress-autoprefixer
include:
  - _javascript
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .idea
  - .jshintrc
  - typings
  - _javascript/app
  - tsconfig.json
  - tslint.json
  - package.json
  - gulpfile.js
  - webpack.config.js
repository: "V-Squared/shop"
permalink: pretty
